### PR TITLE
Use Admin Generator for products

### PR DESCRIPTION
**Pull request by johnnyomair**

### CODE REVIEW

**Review by nsams — APPROVED** [review]

**Review by thomasdax98 — COMMENTED** [review]
This makes me wonder why the API for products is not generated? What's the reason?

It's a bit strange that the Admin is generated now but not the API since
1. the Admin generator is designed to build upon the result of the API generator
2. the API generator is way more advanced than the Admin generator

**Review by thomasdax98 — DISMISSED** [review]

**Comment by johnnyomair** [comment]
> This makes me wonder why the API for products is not generated? What's the reason?
> 
> It's a bit strange that the Admin is generated now but not the API since
> 
> 1. the Admin generator is designed to build upon the result of the API generator
> 2. the API generator is way more advanced than the Admin generator

The main reason why we can't generate the API with the API Generator is the `author` column that's used to demonstrate ACL testing. We could remove that  (and also the respective test). We'll discuss this in today's meeting.

**Review by dkarnutsch — DISMISSED** [review]

**Comment by johnnyomair** [comment]
I've rebased this PR to use the API Generator for products as well (sorry 😬).

**Review by nsams — APPROVED** [review]

**Review by thomasdax98 — APPROVED** [review]

**Review by dkarnutsch — DISMISSED** [review]

**Comment by thomasdax98** [comment]
@johnnyomair Please rebase

**Review by thomasdax98 — APPROVED** [review]

**Pull request merged**
