### PR TITLE
Copy starter from GitLab

### PR DESCRIPTION
**Pull request by max-debug022**

### CODE REVIEW

**Review by johnnyomair — APPROVED** [review]

**Review by dkarnutsch — APPROVED** [review]

**Comment by nsams** [comment]
Could you set a different git author for this code, as you didn't write it yourself.

do we have some bot user? or simply office@vivid-planet.com?

**Comment by max-debug022** [comment]
@nsams Thats a good idea! Ive set the Author to "Vivid Planet <office@vivid-planet.com>".

**Review by nsams — APPROVED** [review]

**Comment by johnnyomair** [comment]
Is this correct?

Git log says it's office@vivid-planet.com, but GitHub still shows @max-debug022 profile? Maybe because there's no profile for office@vivid-planet.com?

image

**Review by thomasdax98 — APPROVED** [review]

**Comment by thomasdax98** [comment]
@johnnyomair Probably. Since the blame shows "Vivid Planet", I think it's okay

**Pull request merged**
